spring.application.name=task-manager

# Conexão Datasource
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/taskdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=taskuser
spring.datasource.password=taskpassword

# Configurações JPA e Hibernate para Spring Boot 4.x
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Propriedades específicas do Hibernate 7
spring.jpa.properties.hibernate.format_sql=true
